services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
      - ./app:/var/www:cached
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    links:
      - php-fpm
    restart: always
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www:cached
    restart: always
    user: "${APP_UID:-10001}:${APP_GID:-10001}"
    environment:
      PHP_IDE_CONFIG: "serverName=validation"
